FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY src/frontend/.next/standalone ./
COPY src/frontend/.next/static ./.next/static
RUN mkdir -p ./public && chown -R nextjs:nodejs /app

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
