FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs && mkdir -p ./public

COPY --chown=nextjs:nodejs src/frontend/.next/standalone ./
COPY --chown=nextjs:nodejs src/frontend/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
